name: deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: checkout code
      uses: actions/checkout@v3

    - name: setup ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.2.2'
        bundler-cache: true

    - name: install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip3 install --upgrade jupyter
        npm install -g purgecss
        npm install -g sass@1.49.11
        npm install -g @mermaid-js/mermaid-cli

    - name: build site
      run: |
        export JEKYLL_ENV=production
        bundle install
        bundle exec jekyll build --lsi

    - name: deploy to github pages
      if: github.event_name != 'pull_request'
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: _site
        branch: gh-pages
