name: deploy jekyll site to pages

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v3
    - name: setup ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.2.2'
        bundler-cache: true
    - name: install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip3 install jupyter
        npm install -g sass
    - name: build with jekyll
      run: bundle exec jekyll build --baseurl "/"
      env:
        jekyll_env: production
    - name: upload artifact
      uses: actions/upload-pages-artifact@v3

  deploy:
    runs-on: ubuntu-22.04
    needs: build
    steps:
    - name: deploy to github pages
      uses: actions/deploy-pages@v4
